### PR TITLE
Clipboard manager module

### LINKED ISSUE #8: Clipboard history module
Widget which shows recent clipboard items & allows re-copying them.

### PR DESCRIPTION
**Pull request by JakeStanger**
Adds new clipboard manager widget, which shows recently copied text/images and allows you to re-copy them.

Currently only supports plain text, and most image types. 

Known issue that large images cause an error when copied from the widget and then pasted into xwayland clients.

This is a bit rough around the edges but I am BORED of working on it, so I'll get it out in the open and polish it properly later™.

Resolves #8

### CODE REVIEW

**Comment by JakeStanger** [comment]
@yavko FYI in regards to #66 this adds a new flag called `clipboard`.

**Comment by yavko** [comment]
> @yavko FYI in regards to #66 this adds a new flag called `clipboard`.

I'm thinking of making it not dependent on a list, and instead use default features. And then if a list is provided not to use default features, which should make it not need to be updated.

**Comment by JakeStanger** [comment]
Ah yeah, that'd be great actually

**Comment by yavko** [comment]
> Ah yeah, that'd be great actually

That reminds me gotta finish it 😳

**Comment by JakeStanger** [comment]
No rush, the next update is gonna take me quite a while to finish anyway. Appreciate the help!

**Pull request merged**
