### PR TITLE
Attempt to fix image blurriness on nix

### LINKED ISSUE #96: Images look really low quality
**Describe the bug**

icons and cover art look blurry, hidpi issue perhaps?

**Expected behavior**

images are displayed at the right resolution

**System information:**
 - Distro: NixOS 23.05
- Compositor: Hyprland
 - Ironbar version: master at `0.11`

**Additional context**

probably hidpi

**Screenshots**

icon image
another icon (only play is icon) 
image

### PR DESCRIPTION
**Pull request by yavko**
Should maybe fix #96

### CODE REVIEW

**Comment by yavko** [comment]
@JakeStanger IT FIXES IT!!!!

**Comment by yavko** [comment]
except for tray icons, idk but they super low quality (also this is with css dim effect, so they look less demonic as they used to)
image

**Comment by yavko** [comment]
Still doesn't look perfect tho, hmm
image

**Comment by JakeStanger** [comment]
Definitely a massive improvement. I think tray icons are being handled separately at the moment, so I'll try and address that. Cheers!

**Pull request merged**
