### PR TITLE
Update hyprland-rs

### PR DESCRIPTION
**Pull request by nyadiia**
Hyprland recently changed the socket that is used for the IPC. This makes the hyprland workspaces module not work in the latest version.

Currently this at the latest git version of hyprland-rs. As of now, the socket only works with the new location and not both. It seems like this isn't intended however. https://github.com/hyprland-community/hyprland-rs/pull/218

### CODE REVIEW

**Comment by JakeStanger** [comment]
Cheers. I'll hold off merging this until it works on both versions, as otherwise this breaks Ironbar against the latest Hyprland tagged release.

**Comment by yavko** [comment]
I would recommend against merging this as this depends on hyprland-rs git which would prevent ironbar from being updated on crates.io

**Comment by yavko** [comment]
Guys i pushed a fix, ive waited too long, please please please someone just test it 😭 https://github.com/hyprland-community/hyprland-rs/pull/218

**Comment by nyadiia** [comment]
i'm sorry, i'm not able to test it rn,, i might be able to test it tomorrow or later tonight

**Comment by yavko** [comment]
i have confirmation it works older releases, now i need someone to test a newer commit

**Comment by nyadiia** [comment]
tested on latest ( aur -git version ) and it works on both git and latest tagged version

**Comment by nyadiia** [comment]
looks like the nix builds are failing from the hyprland-rs version being a git version.. i don't think this should be merged until there's a tagged release for it

**Comment by yavko** [comment]
Updated the patch again to fix a very specific edge case

**Comment by JakeStanger** [comment]
> looks like the nix builds are failing from the hyprland-rs version being a git version.. i don't think this should be merged until there's a tagged release for it

It should be possible to override the specific nix dep to use Git, although given there's 3 builders that's probs need to be done that 3 different ways...

**Comment by yavko** [comment]
> > looks like the nix builds are failing from the hyprland-rs version being a git version.. i don't think this should be merged until there's a tagged release for it
> 
> It should be possible to override the specific nix dep to use Git, although given there's 3 builders that probs need to be done that 3 different ways...

I implemented 3 builders but realistically we should just choose the one with the best caching and get rid of the other ones as they can't even be changed by the user

**Comment by yavko** [comment]
Merged the PR which shouldn't have any edge cases, sorry for being annoying with asking for testers, but I will try to get an alpha release out tomorrow (I have too much work today so sorry about that) which should allow an update to be pushed to crates.io

**Comment by yavko** [comment]
release published https://github.com/hyprland-community/hyprland-rs/releases/tag/0.4.0-alpha.1

**Comment by nyadiia** [comment]
world if i could spell ( reason for force pushes ). anyways this should be good now

**Review by yavko — APPROVED** [review]

**Comment by JakeStanger** [comment]
There's still conflicts that need resolving before I can merge. Can you rebase onto latest master please?

 If they're in the lock file I'd just do whatever, then delete and rebuild to regen.

**Comment by nyadiia** [comment]
oh god. hm so i may have to redo that

**Comment by nyadiia** [comment]
figured it out 👍

**Review by JakeStanger — APPROVED** [review]

**Comment by JakeStanger** [comment]
Cheers :)

**Pull request merged**
