### PR TITLE
build(nix): fix naersk build broken when using non-default features

### LINKED ISSUE #520: When setting "features" through HomeManager config in Nix, cargo throws an error
**Describe the bug**
When I set the "features" option in `programs.ironbar.features`, I get a build error:
```
last 10 log lines:
> cargo --no-default-features -F "cli,http,config+json,clipboard,clock,focused,launcher,music+all,notification,sys_info,tray,upower,volume" build $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
> error: unexpected argument '--no-default-features' found
>
>   tip: 'build --no-default-features' exists
>
> Usage: cargo [OPTIONS] [COMMAND]
>        cargo [OPTIONS] -Zscript <MANIFEST_RS> [ARGS]...
>
> For more information, try '--help'.
> [naersk] cargo returned with exit code 1, exiting
```

**To Reproduce**
1. Set `programs.ironbar.features` to something else than `[]`
2. Try rebuilding the system
3. Get the error

**Expected behavior**
Project builds.

**System information:**
 - Distro: NixOS unstable
- Compositor: Hyprland/Trying to make it work in niri as I'm assuming, workspace specific code makes it not show up (maybe?)
 - Ironbar version: 0.15.0-pre (dictated by the flake)

**Configuration**
> N/A

**Additional Context**
I made sure to run nix flake update and try to build again in case the bug was fixed, but it wasn't.

I also took a look into `default.nix` and all does seem good, so I'm not sure if it's the ironbar flake or naersk issue, so sorry if this issue is not relevant here. 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by JakeStanger**
Fixes #520

### CODE REVIEW

**Comment by yavko** [comment]
Sorry about this mistake 😔

**Comment by JakeStanger** [comment]
Mistakes happen, it's cool. I've got Nix setup on my machine and just about enough grasp to be able to check things myself in future, but please do test things before PR-ing them.

**Comment by yavko** [comment]
> Mistakes happen, it's cool. I've got Nix setup on my machine and just about enough grasp to be able to check things myself in future, but please do test things before PR-ing them.

I think I tested only the crane builder tbh, but it's been so long I don't even remember if I tested crane.

**Comment by tukanoidd** [comment]
just checked, it works, can be merged :)

**Pull request merged**
