### PR TITLE
More tray fixes

### PR DESCRIPTION
**Pull request by JakeStanger**
Fixes tray icons not disappearing on program close.
Fixes menus not attaching to tray icons on bars other than the primary.

### CODE REVIEW

**Comment by ToxicMushroom** [comment]
@JakeStanger [5aa9f37](https://github.com/JakeStanger/ironbar/pull/782/commits/5aa9f37fe4ff76d9ef61e8c0aacc110ecb9a89c3) opens 2 menus for elements that did not have this issue previously.

**Comment by ToxicMushroom** [comment]
I kinda feel bad for reporting all these issues T.T

**Comment by JakeStanger** [comment]
Ahh of course it does, yes that should be an easy fix. Just need to check/disconnect the old one when an event is received for the new one. 

The issues are annoying but it's my own fault. Reporting them is *not* annoying, and is hugely appreciated & always will be. I want Ironbar to be as stable as it can be, and at least documented where it isn't, and detailed reports like this help a lot.

**Comment by JakeStanger** [comment]
> Since commit [5aa9f37](https://github.com/JakeStanger/ironbar/pull/782/commits/5aa9f37fe4ff76d9ef61e8c0aacc110ecb9a89c3) clicking a tray item can open 2 menus for elements that did not have the issue Fixes menus not attaching to tray icons on bars other than the primary. previously.

Resolved by #788

**Pull request merged**
