### PR TITLE
ci(nix): Add Crane and Naersk builders

### PR DESCRIPTION
**Pull request by yavko**
Right now the builder is on crane, but it's switchable to naersk (one string)

### CODE REVIEW

**Comment by yavko** [comment]
Great the merge broke the lockfile

**Comment by JakeStanger** [comment]
The build took twice as long as usual. Is that normal with crane? 

My concern is that the extended build could outweigh the caching, although I guess we might have to see how that plays out.

**Comment by yavko** [comment]
> The build took twice as long as usual. Is that normal with crane? 
> 
> My concern is that the extended build could outweigh the caching, although I guess we might have to see how that plays out.

I think it's because it's running build, check, and test

**Comment by JakeStanger** [comment]
Is there the option to turn some of those off? I don't really think we need to run both `build` and  `check`, or `test` (since there's no GTK tests rn) in the Nix build if those are running in the main build, we only really need to check it compiles.

**Comment by yavko** [comment]
> Is there the option to turn some of those off? I don't really think we need to run both `build` and `check`, or `test` (since there's no GTK tests rn) in the Nix build if those are running in the main build, we only really need to check it compiles.

There is (this is also for test):
image

**Comment by yavko** [comment]
We can try naersk instead to see if it does caching better for some reason the dependencies weren't cached with crane

**Comment by JakeStanger** [comment]
Looks like the speed is pretty much on par with the original, plus some extra time for caching, so I think we can roll with that. Are you able to squash your commits down into one or two, and use the `ci(nix)` prefix pls, then I'll merge this?

**Comment by yavko** [comment]
> Looks like the speed is pretty much on par with the original, plus some extra time for caching, so I think we can roll with that. Are you able to squash your commits down into one or two, and use the `ci(nix)` prefix pls, then I'll merge this?

Idk how to squash it cuz of the merge commit, I swear the github merge conflict resolver always makes you shoot yourself in the foot by not rebasing

**Comment by JakeStanger** [comment]
Yeah, I always tend to rebase PR commits because merges just add noise and make it difficult to do anything. Give me a bit, I'll see if I can sort it :)

**Comment by yavko** [comment]
> Yeah, I always tend to rebase PR commits because merges just add noise and make it difficult to do anything. Give me a bit, I'll see if I can sort it :)

Thanks! I have very limited amount of knowledge on how to do any merging with git

**Comment by JakeStanger** [comment]
Don't think I would have worked this out in a million years: https://stackoverflow.com/a/69827502

**Comment by yavko** [comment]
> Don't think I would have worked this out in a million years: [stackoverflow.com/a/69827502](https://stackoverflow.com/a/69827502)

Can u co-author me in the commit? I want to have more contributions on my gh profile lol

**Comment by JakeStanger** [comment]
Oh crap sorry, you *were* I'm not sure how I lost that. Fixed now :)

Definitely not trying to steal your glory, I want you credited for your work in the repo.

Will merge as soon as the build completes, thanks again!

**Comment by yavko** [comment]
Thanks hehe

**Comment by yavko** [comment]
Huh normal build failed
image

**Comment by JakeStanger** [comment]
Apparently I committed up every test file I had lying around with this :|

**Pull request merged**
